import '../globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Instagram Reels & Post Downloader',
  description: 'Generated by create next app',
}

const Header = () => {
    return(
        <header className="bg-white p-8 shadow-lg w-full">
            <div className="container mx-auto">
            <div className="flex justify-between items-center">
                <div><span className="font-bold uppercase text-md md:text-2xl">IG Downloader</span> <small className="text-2xs md:text-sm">Reels & Post</small></div>
                <nav className="">
                <div className="hidden w-full md:flex md:w-auto md:order-1" id="collapseExample" data-te-collapse-item>
                    <ul className="flex p-4 flew-row space-x-8 font-medium">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <li>
                    <a href="/contact">Contact</a>
                    </li>
                    </ul>
                </div>
                </nav>
            </div>
            </div>
        </header>
    );
}

export default Header;